- name: Prepare cni plugins
  set_fact:
    github_project: https://github.com/containernetworking/plugins
    github_asset_name_pattern: "^cni-plugins-amd64-.+\\.tgz$"
    github_asset_local_path: "{{ cni_plugins_local }}"

- name: Check cni plugins on disks
  stat:
    path: "{{ github_asset_local_path }}"
  register: cni_local_state

- name: Download cni plugins
  include_tasks: ../../common/tasks/github-release.yml
  when: not cni_local_state.stat.exists