- name: Upload package
  include_tasks: ../../kube-release-package/tasks/upload-package.yml

- name: Load images
  shell: |
    [[ ! -d kubernetes/server/bin ]] && tar zxf kubernetes-server-linux-amd64.tar.gz
    pushd kubernetes/server/bin > /dev/null
    for tar in *.tar; do
      docker tag `docker load -qi ${tar} | awk '{ print $3 }'` `basename -s.tar ${tar}`:{{ kube_release_version }}
    done
    cp kubeadm kubectl kubelet /usr/bin
    popd > /dev/null
    rm -rf kubernetes
  args:
    chdir: "{{ remote_app_path }}"
    executable: /bin/bash
  register: debug_extracting

- name: Install bash completion
  shell: |
    mkdir -p /root/.kube/
    kubectl completion bash > ~/.kube/completion.bash.inc
    printf "
    # Kubectl shell completion
    source '$HOME/.kube/completion.bash.inc'
    " >> /root/.bash_profile
  args:
    executable: /bin/bash

- debug:
    msg: "{{ debug_extracting }}"