- name: Upload package
  include_tasks: ../../kube-release-package/tasks/upload-package.yml

- name: Load images
  shell: |
    [[ ! -d kubernetes/server/bin ]] && tar zxf kubernetes-server-linux-amd64.tar.gz
    pushd kubernetes/server/bin > /dev/null
    for tar in *.tar; do
      docker load -i ${tar}
    done
    cp kubeadm kubectl kubelet /usr/bin
    popd > /dev/null
    rm -rf kubernetes
  args:
    chdir: "{{ remote_app_path }}"
    executable: /bin/bash
  register: debug_extracting

- debug:
    msg: "{{ debug_extracting }}"