- name: Initialize API server endpoint for single master cluster
  include_tasks: single-master-endpoint.yml
  when: "{{ groups['master'] | length == 1 }}"

- name: Initialize API server endpoint for HA cluster
  include_tasks: ha-endpoint.yml
  when: "{{ groups['master'] | length > 2 }}"