- name: Check CA existence
  stat:
    path: "{{ ca }}"
  register: ca_state

- name: Check CA key existence
  stat:
    path: "{{ ca_key }}"
  register: ca_key_state

- name: Generate CNF file
  template:
    src: "cnf-ca.j2"
    dest: "{{ ca }}.cnf"
  when: not cnf_state.stat.exists

- name: Generate CA and private Key
  shell: |
    openssl req -newkey rsa:4096 -nodes -keyout {{ ca_key }} -x509 -config {{ ca }}.cnf -days 3650 -out {{ ca }}
  when: not ca_state.stat.exists or not ca_key_state.stat.exists