- name: Load image {{ etcd_image }}
  include_tasks: ../../cache/tasks/image.yml
  vars:
    image: "{{ etcd_image }}"

- name: Load image osixia/keepalived:1.4.5
  include_tasks: ../../cache/tasks/image.yml
  vars:
    image: osixia/keepalived:1.4.5

- name: Load image osixia/keepalived:1.4.5
  include_tasks: ../../cache/tasks/image.yml
  vars:
    image: haproxy:1.7-alpine